export enum BiomeType {
    FertilePlain = 'FertilePlain',
    Forest = 'Forest',
    Swamp = 'Swamp',
    RedDesert = 'RedDesert',
    TropicalJungle = 'TropicalJungle',
    FrozenTundra = 'FrozenTundra',
    Mountains = 'Mountains',
    Wasteland = 'Wasteland',
    SaltFlats = 'SaltFlats',
    CrystalSpires = 'CrystalSpires',
    LavaFlows = 'LavaFlows',
    ObsidianSpires = 'ObsidianSpires',
    GlowingCaves = 'GlowingCaves',
    PirateOutpost = 'PirateOutpost',
    // Non-colonizable
    TimeRift = 'TimeRift',
    BlackHole = 'BlackHole',
    StormField = 'StormField',
    PrismField = 'PrismField',
}
